package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<title>KLEE教育</title>\r\n");
      out.write("<link type=\"image/x-icon\" rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("<link href=\"css/head_nav.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/head.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/head.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slide.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--头部导航栏-->\r\n");
      out.write("\t<div id=\"head_nav\">\r\n");
      out.write("\t\t<div id=\"head_menu\">\r\n");
      out.write("\t\t\t<ul class=\"head_ul\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/logo3.png\" class=\"head_logo\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/logo_4.png\" class=\"head_logo_1\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/faith.png\" class=\"head_logo1\" /></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\" class=\"head_li\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color:#09C;font-weight:bold;\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"head_li\" id=\"head_li_from\">\r\n");
      out.write("\t\t\t\t\t<a href=\"html/business_system.jsp\" class=\"head_font_size\" >课程体系</a>\r\n");
      out.write("\t\t\t\t\t<!-- <ul class=\"head_nav_nav_none\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"html/yewu.html\"  class=\"head_font_size\" class=\"head_nav_yw_tx\" class=\"head_li\">业务体系</a></li>\r\n");
      out.write("\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"html/step_in.jsp\" class=\"head_li\">走进KLEE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/time_axis.jsp\" class=\"head_li\">发展历程</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/developer.jsp\" class=\"head_li\">论坛.活动</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/bangzhu.jsp\" class=\"head_li\">帮助</a></li>\r\n");
      out.write("\t\t\t\t");

					String name = (String) session.getAttribute("name");
					if (name == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"html/l_zhuce.jsp\" class=\"DL_zc\">注册</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"entry()\" class=\"DL_\">登录</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"DL_name\" onclick=\"javascript:alert('暂时不能提供查看个人信息')\">欢迎您:");
      out.print(name);
      out.write("</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"exit()\" class=\"DL_E\">退出</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--登录框-->\r\n");
      out.write("\t<div id=\"entry_box\">\r\n");
      out.write("\t\t<div class=\"dl_box\">\r\n");
      out.write("\t\t\t<div id=\"entry\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t<span id=\"entry_span1\" onClick=\"entryOne()\">请输入用户名</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span3\"></span><span id=\"entry_span3_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"entry_one\" name=\"username\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entryOne()\" onBlur=\"text()\" /><br /> <br /> <br /> <span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span2\" onClick=\"entry_one1()\">请输入登陆密码</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span4\"></span><span id=\"entry_span4_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"entry_two\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entry_one1()\" onBlur=\"text1()\" /><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"GO>>\" id=\"entry_submit\" onClick=\"decision()\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <span><a href=\"html/link.jsp\"\r\n");
      out.write("\t\t\t\tclass=\"entry_span_1\">忘记密码&gt;&gt;</a></span> -->\r\n");
      out.write("\t\t\t<span><a href=\"html/l_zhuce.jsp\" class=\"entry_span_2\">注册&gt;&gt;</a>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--搜索栏-->\r\n");
      out.write("\t<div class=\"search_box\">\r\n");
      out.write("\t\t<div class=\"search\" id=\"search\">\r\n");
      out.write("\t\t\t<div class=\"search_xuexi\"></div>\r\n");
      out.write("\t\t\t<div class=\"S_earch\">\r\n");
      out.write("\t\t\t\t<div class=\"search_kc\">\r\n");
      out.write("\t\t\t\t\t<!-- onClick=\"search_2()\" -->\r\n");
      out.write("\t\t\t\t\t搜索\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"search_kc_1\"></span>\r\n");
      out.write("\t\t\t\t\t<div id=\"search_kc_2\">讲师&nbsp;&nbsp;&nbsp;&nbsp;</div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"search_textK\" />\r\n");
      out.write("\t\t\t\t<div class=\"search_ss\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search_logo\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--VIP快捷菜单-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"search_VIP\">\r\n");
      out.write("\t\t\t\t<div class=\"search_VIP_box\">\r\n");
      out.write("\t\t\t\t\t<span class=\"search_VIP_1\" id=\"search_span\"></span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"search_span\"><a href=\"html/link.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"search_VIP_txt\">VIP课程</a></span>\r\n");
      out.write("\t\t\t\t\t<!-- VIP课程 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"search_VIP_box1\">\r\n");
      out.write("\t\t\t\t\t<span class=\"search_VIP_2\" id=\"search_span\"></span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"search_span\"><a href=\"html/link.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"search_VIP_txt1\">免费体验课</a></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"search_kJie\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" class=\"search_a\">雅思精准预测</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" class=\"search_a\" id=\"search_a1\">Web前端精品课</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" class=\"search_a\">趣味英</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" class=\"search_a\" id=\"search_a1\">上海市公务员考试</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--导航区-->\r\n");
      out.write("\t<div class=\"nav\">\r\n");
      out.write("\t\t<!--导航背景区-->\r\n");
      out.write("\t\t<div class=\"nav_bg\" id=\"outer\">\r\n");
      out.write("\t\t\t<ul id=\"inner\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/66.jpg\" width=\"880\" height=\"290\" alt=\" \"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/22.jpg\" width=\"880\" height=\"290\" alt=\" \"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/33.jpg\" width=\"880\" height=\"290\" alt=\" \"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/44.jpg\" width=\"880\" height=\"290\" alt=\" \"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/55.jpg\" width=\"880\" height=\"290\" alt=\" \"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/11.jpg\" width=\"880\" height=\"290\" alt=\" \"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div id=\"left\">L</div>\r\n");
      out.write("\t\t\t<div id=\"right\">R</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/slide.js\"></script>\r\n");
      out.write("\t\t<!--导航栏区-->\r\n");
      out.write("\t\t<div class=\"nav_nav\" id=\"nav_nav\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"nav_type\"><img src=\"images/menu.png\" />&nbsp;&nbsp;全部课程</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav_title\" style=\"border-left:4px solid #F30;\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"nav_icon1\" id=\"nav_icon1\"></span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"nav_h2\">IT培训</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_jt\"></div> <span class=\"nav_title_txt1\" id=\"nav_T\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"html/link_java.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt2\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt3\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_2nav\" id=\"nav_2nav1\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"margin-top:27px;\"><span class=\"nav_2nav_title\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"nav_h2\">&nbsp;&nbsp;IT培训</h2></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"width:310px;height:1px;background:#CACACA;\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link_java.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav_title\" style=\"border-left:4px solid #09C;\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"nav_icon1\" id=\"nav_icon2\"></span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"nav_h2\">职业技能</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_jt\"></div> <span class=\"nav_title_txt1\" id=\"nav_T\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"html/link.jsp\">淘宝电商</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt2\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;UG产品设计</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_2nav\" id=\"nav_2nav2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"margin-top:27px;\"><span class=\"nav_2nav_title\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"nav_h2\">&nbsp;&nbsp;IT培训</h2></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"width:310px;height:1px;background:#CACACA;\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav_title\" style=\"border-left:4px solid #0C0;\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"nav_icon1\" id=\"nav_icon3\"></span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"nav_h2\">语言培训</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_jt\"></div> <span class=\"nav_title_txt1\" id=\"nav_T\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"html/link.jsp\">日语</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt2\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;韩语</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt3\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;泰语</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_2nav\" id=\"nav_2nav3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"margin-top:27px;\"><span class=\"nav_2nav_title\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"nav_h2\">&nbsp;&nbsp;IT培训</h2></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"width:310px;height:1px;background:#CACACA;\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav_title\" style=\"border-left:4px solid #630;\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"nav_icon1\" id=\"nav_icon4\"></span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"nav_h2\">兴趣爱好</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_jt\"></div> <span class=\"nav_title_txt1\" id=\"nav_T\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"html/link.jsp\">农业</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt2\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;手工DIY</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span> <span class=\"nav_title_txt3\"\r\n");
      out.write("\t\t\t\t\tid=\"nav_T\"> <a href=\"html/link.jsp\">&nbsp;&nbsp;吉他</a>\r\n");
      out.write("\t\t\t\t</span> <span style=\"color:#CCC;\">|</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav_2nav\" id=\"nav_2nav4\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"margin-top:27px;\"><span class=\"nav_2nav_title\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"nav_h2\">&nbsp;&nbsp;IT培训</h2></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"width:310px;height:1px;background:#CACACA;\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt1\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">JAVA</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt2\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;PHP</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span class=\"nav_title_txt3\" id=\"nav_T1\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"html/link.jsp\">&nbsp;&nbsp;安卓</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li id=\"nav_bottom\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav_kuaiJ\" id=\"nav_kuaiJ\">\r\n");
      out.write("\t\t\t<img src=\"images/qunjv1.jpg\" width=\"293\" height=\"115\" /> <img\r\n");
      out.write("\t\t\t\tsrc=\"images/guokao1.jpg\" width=\"293\" height=\"115\" /> <img\r\n");
      out.write("\t\t\t\tsrc=\"images/job1.jpg\" width=\"293\" height=\"115\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--精选课程-->\r\n");
      out.write("\t<div class=\"chosen\">\r\n");
      out.write("\t\t<!-- <h1></h1>\r\n");
      out.write("\t\t<span onClick=\"chosen(1)\" id=\"chosen_nav\" class=\"chosen_nav2\">师资力量</span>\r\n");
      out.write("\t\t<span onClick=\"chosen(2)\" id=\"chosen_nav1\" class=\"chosen_nav2\">学员风采</span> -->\r\n");
      out.write("\t\t<div class=\"chosen_border\">精选课程</div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\"><a href=\"html/link.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/221.png\" width=\"260\" height=\"160\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">全民营销----营销高手的成长秘诀</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;叶博武</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥6500</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新1课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥4500</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\"><a href=\"html/link.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/222.png\" width=\"260\" height=\"160\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">游戏动作全能学习班</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;贾国瑞</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥8600</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新40课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥5500</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\"><a href=\"html/link.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/220.png\" width=\"260\" height=\"160\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">社会人际学习班</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;罗文杰</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥6500</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新20课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥4000</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\" style=\"margin-right:0px;\"><a\r\n");
      out.write("\t\t\t\thref=\"html/link.jsp\"><img src=\"images/228.jpg\" width=\"260\"\r\n");
      out.write("\t\t\t\t\theight=\"160\" /><img src=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">韩语高级班--零基础入门学习班</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;付秀鹏</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥8000</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新20课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥6000</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--职业技能-->\r\n");
      out.write("\t<div class=\"chosen\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"chosen_border\">职业技能</div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\"><a href=\"html/link.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/IT2.PNG\" width=\"260\" height=\"160\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">PS数码后期实战班.调色.精修.磨皮.设计套版</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;付秀鹏</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥5998</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新41课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥4500</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\"><a href=\"html/link.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/IT3.PNG\" width=\"260\" height=\"160\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">影视动画全面入门</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;罗文杰</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥5500</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新21课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥4500</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\"><a href=\"html/link.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/IT4.PNG\" width=\"260\" height=\"160\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">HTML高级开发,零基础10天入门</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;小瑞</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥7980</s></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新10课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥2500</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"chosen_nav1\" style=\"margin-right:0px;\"><a\r\n");
      out.write("\t\t\t\thref=\"html/link.jsp\"><img src=\"images/IT5.PNG\" width=\"260\"\r\n");
      out.write("\t\t\t\t\theight=\"160\" /><img src=\"images/sp.png\" class=\"chosen_nav_sp\" /></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" id=\"collective_font\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"html/link.jsp\">3D&nbsp;&nbsp;Max零基础最佳选择,做室内设计高手</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"collective_font\" style=\"float:left;color:#F30;\">&nbsp;&nbsp;主讲老师:</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#09F;float:left\" class=\"collective_font\">&nbsp;&nbsp;叶博武</li>\r\n");
      out.write("\t\t\t\t\t<li><s\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color:#666;float:right;margin-left:30px;line-height:30px;\">￥6500</s>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"html/link.jsp\" style=\"float:left;color:#606;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"collective_font\">&nbsp;&nbsp;已更新101课时</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"color:#0C6;float:right;\">￥9500</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--内容-->\r\n");
      out.write("\t<div id=\"bg\">\r\n");
      out.write("\t\t<div class=\"middle_box\">\r\n");
      out.write("\t\t\t<div class=\"middle_box_lanl\">\r\n");
      out.write("\t\t\t\t<h1 class=\"middle_nav\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"middle_a\">语言学习</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" style=\"float:left;\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/t1.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"lanr\">\r\n");
      out.write("\t\t\t\t<div class=\"lanr1\" style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">推荐</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">英语考试</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">韩语</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">日语</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">最新发布</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--内容-->\r\n");
      out.write("\t\t\t\t<div class=\"lanr2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"lanul\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/y1.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"想知道美语怎么说吗\">想知道美语怎么说吗</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥3500</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">高级讲师：付秀鹏<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/new.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/y2.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"90后英语：iTop-[英语求职]\">90后英语：iTop-[英语求职]</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥3800</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">高级讲师：罗文杰<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/hot.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/h4.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"和韩国外教SmallRui老师【外教班】\">和韩国外教SmallRui老师【外教班】</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥4800</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">高级讲师：小瑞<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/new.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/h1.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"疯狂韩语【初级班】\">疯狂韩语【初级班】</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥2600</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">知名讲师：叶博武<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/hot.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/r1.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"【精品课】实战、趣味学日语,日语入门到精通\">【精品课】实战、趣味学日语,日语入门到精通</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\" style=\"color:#099;\">免费</span><b></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">高级讲师：XXX</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/r3.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"看动漫，玩转简单日语\">看动漫，玩转简单日语</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\" style=\"color:#099;\">免费</span><b></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">高级讲师：XXX</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"lanr3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"order\">\r\n");
      out.write("\t\t\t\t\t\t<h2>免费排行</h2>\r\n");
      out.write("\t\t\t\t\t\t<h2>付费排行</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"orderul\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"order1\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">【精品课】实战、趣味学日语 </a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"order11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/9.jpg\" width=\"90\" height=\"50\"></a> <span>6002人</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i>小瑞学院</i>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order2\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">五个定理学好语法</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order3\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">雅思35天极限挑战【环球】 </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order4\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">11.23-11.29-雅思哥学习班正式开课\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order5\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">【精品课程】韩语零基础</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order6\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">小瑞【韩语】在线课堂</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order7\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">和EXO欧巴们一起学韩语</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order8\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">大家的日语1收费VIP班</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order9\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">明王道VIP直播活动课 </a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"bg\">\r\n");
      out.write("\t\t<div class=\"middle_box\">\r\n");
      out.write("\t\t\t<div class=\"middle_box_lanl\">\r\n");
      out.write("\t\t\t\t<h1 class=\"middle_nav\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"middle_a\">IT培训</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" style=\"float:left;\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/yunyan1.jpg\" width=\"240\" height=\"420\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"lanr\">\r\n");
      out.write("\t\t\t\t<div class=\"lanr1\" style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">设计制作</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">编程开发</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">最新发布</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--内容-->\r\n");
      out.write("\t\t\t\t<div class=\"lanr2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"lanul\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/s1.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"CAD绘图设计班\">CAD绘图设计班</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥8888</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">主讲老师：罗文杰<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/new.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/s2.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"solidworks案例教程\">solidworks案例教程</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥5980</span><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">主讲老师：小瑞<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/hot.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/s3.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"平面设计从零基础开始--大师带你走向辉煌\">平面设计从零基础开始--大师带你走向辉煌</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥6800</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">主讲老师：付秀鹏</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/s4.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"PS/AI/CDR高端平面广告设计班\">PS/AI/CDR高端平面广告设计班</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥3800</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">主讲老师：付秀鹏<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/hot.png\" class=\"middle_img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/s5.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"CAD快速入门教程\">CAD快速入门教程</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\" style=\"color:#099;\">免费</span><b></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">主讲老师：叶博武</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hotula1\"><img src=\"images/s6.jpg\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula2\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"PHP网站开发高级工程师班级，士兵课程\">3Dmax建模(快速入门)</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hot3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"middle_money\">￥4500</span><b></b> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\" class=\"hotula3\">主讲老师：叶博武</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"lanr3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"order\">\r\n");
      out.write("\t\t\t\t\t\t<h2>免费排行</h2>\r\n");
      out.write("\t\t\t\t\t\t<h2>付费排行</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"orderul\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"order1\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">PS真正零基础到精通教程 </a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"order11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/ps.png\" width=\"60\" height=\"50\"></a> <span>6002人</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i>XX学院</i>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order2\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">CAD/UG模具设计高级结构班\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order3\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">VIP课堂PS软件零基础</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order4\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">蓝铅笔sai插画漫画基础</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order5\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">Java基础进阶高级工程师，一切由你决定</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order6\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">CTO学院Linux运维架构师\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order7\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">【C#零基础】两周制作</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order8\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">零基础编程,原价2000元</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"order9\"><b></b><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:alert('正在紧急开发中，给您带来的不便请谅解')\">DIV+CSS零基础到实战</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 版权部分修改版 -->\r\n");
      out.write("\t<div class=\"bottom_banquan\">\r\n");
      out.write("\t\t<div class=\"bottom_bg_color\">\r\n");
      out.write("\t\t\t<div class=\"bottom_box\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"lianxi_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bottom_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon1.png\" class=\"lianxi_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:viod(0)\" title=\"中国陕西省西安市长安区下北良村西安科技大学高新学院\">中国陕西省西安市长安区下北良村西安科技大学高新学院</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon3.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"tel:15596885995\" title=\"400-888-8888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">400-888-8888</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon2.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;margin-top:-8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"mailto:603049583@qq.com\" title=\"klee@163.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">klee@163.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--留言板  -->\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_right\">\r\n");
      out.write("\t\t\t\t\t<form onsubmit=\"tijiao()\" name=\"from_bus\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bottom_lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">邮&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"position:relative;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"youxiang(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"youxiang_box\" id=\"youxiang_\">邮箱格式有误</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang2\" name=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\" width=\"80px\" valign=\"top\">留言内容:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"kong\" cols=\"30\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang3\" style=\"resize:none;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><div class=\"lianxi_right_tijiao\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"liuyan()\">Submit</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom_banquan_bq\">\r\n");
      out.write("\t\t\t<div class=\"bottom_banquan_center\">\r\n");
      out.write("\t\t\t\t<div class=\"banquan_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"banquan_bufen\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">Copyright © 2015 xike2-3zu. All\r\n");
      out.write("\t\t\t\t\t\tRightsReserved.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">西科软件开发二班第三组 版权所有 | 贾国瑞 | 罗文杰 | 叶博武 | 付秀鹏</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--浮动猫链接-->\r\n");
      out.write("\t<div class=\"float_box\">\r\n");
      out.write("\t\t<div class=\"float\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"float_a\">返回顶部 <span class=\"float_bg\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"float1\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"float_a1\">关注微信 <span\r\n");
      out.write("\t\t\t\tclass=\"float_bg1\"></span> <img src=\"images/wx.JPG\" width=\"150\"\r\n");
      out.write("\t\t\t\theight=\"150\" class=\"weixin\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
