package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class bangzhu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("<title>帮助</title>\r\n");
      out.write("<link type=\"image/x-icon\" rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("<link href=\"css/head_nav.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/head.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/entry.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".bg_en {\r\n");
      out.write("\twidth: 1349px;\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\tbackground: url(\"html/images/05.jpg\") no-repeat;\r\n");
      out.write("\tbackground-size: 1350px 700px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg_color {\r\n");
      out.write("\twidth: 1349px;\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.8);\r\n");
      out.write("}\r\n");
      out.write("/*帮助中心_CSS开始*/\r\n");
      out.write(".helpbox {\r\n");
      out.write("\twidth: 1198px;\r\n");
      out.write("\theight: 900px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tborder: 1px #dcdcdc solid;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("/*帮助中心左边*/\r\n");
      out.write(".helpboxL {\r\n");
      out.write("\twidth: 219px;\r\n");
      out.write("\tborder-right: 1px #dcdcdc solid;\r\n");
      out.write("\theight: 900px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxL ul {\r\n");
      out.write("\twidth: 219px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxL ul li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 219px;\r\n");
      out.write("\tborder-bottom: 1px #CCC solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helplli1 {\r\n");
      out.write("\theight: 248px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helplli2 {\r\n");
      out.write("\theight: 149px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxL ul li.helplli3 {\r\n");
      out.write("\tborder-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("/*大标题*/\r\n");
      out.write(".helpboxL ul h2 {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tcolor: #666666;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 197px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tmargin: 26px 0px 10px 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#teacher,#company {\r\n");
      out.write("\tmargin: 11px 0px 10px 24px;\r\n");
      out.write("}\r\n");
      out.write("/*LEFT——A*/\r\n");
      out.write(".helpboxL ul a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 197px;\r\n");
      out.write("\theight: 42px;\r\n");
      out.write("\tpadding-left: 18px;\r\n");
      out.write("\tborder-left: 4px #fff solid;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tline-height: 42px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("}\r\n");
      out.write("/*a:hover*/\r\n");
      out.write(".helpboxL ul a:hover {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 197px;\r\n");
      out.write("\theight: 42px;\r\n");
      out.write("\tpadding-left: 18px;\r\n");
      out.write("\tborder-left: 4px #e5e5e5 solid;\r\n");
      out.write("\tbackground-color: #f2f2f2;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tline-height: 42px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("}\r\n");
      out.write("/*a。now*/\r\n");
      out.write(".helpboxL ul li a.now {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 197px;\r\n");
      out.write("\theight: 42px;\r\n");
      out.write("\tpadding-left: 18px;\r\n");
      out.write("\tborder-left: 4px #039ae3 solid;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tline-height: 42px;\r\n");
      out.write("\tcolor: #039ae3;\r\n");
      out.write("}\r\n");
      out.write("/*帮助中心右边*/\r\n");
      out.write(".helpboxR {\r\n");
      out.write("\twidth: 978px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 900px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxR2 {\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\tmargin: 40px 0px 0px 30px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxR2 h1 {\r\n");
      out.write("\tborder-bottom: 1px #CCC solid;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tpadding-bottom: 17px;\r\n");
      out.write("\tcolor: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxR2 h3 {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tmargin: 24px 0px 7px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".helpboxR2 p {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tline-height: 32px;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-indent: 12px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"headNav()\">\r\n");
      out.write("\t<!--头部导航栏-->\r\n");
      out.write("\t<div id=\"head_nav\">\r\n");
      out.write("\t\t<div id=\"head_menu\">\r\n");
      out.write("\t\t\t<ul class=\"head_ul\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/logo3.png\" class=\"head_logo\" width=\"55\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/logo_4.png\" width=\"70\" class=\"head_logo_1\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/faith.png\" class=\"head_logo1\" /></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\" class=\"head_li\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"head_li\" id=\"head_li_from\"><a\r\n");
      out.write("\t\t\t\t\thref=\"html/business_system.jsp\" class=\"head_font_size\">课程体系</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"head_nav_nav_none\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"html/yewu.html\" class=\"head_font_size\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"head_nav_yw_tx\" class=\"head_li\">业务体系</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/step_in.jsp\" class=\"head_li\">走进KLEE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/time_axis.jsp\" class=\"head_li\">发展历程</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/developer.jsp\" class=\"head_li\">论坛.活动</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/bangzhu.jsp\" class=\"head_li\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color:#09C;font-weight:bold;\">帮助</a></li>\r\n");
      out.write("\t\t\t\t");
String name = (String)session.getAttribute("name");
            if(name == null)
            {	
            	
      out.write("\r\n");
      out.write("            \t<li><a href=\"html/l_zhuce.jsp\" class=\"DL_zc\">注册</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"entry()\" class=\"DL_\">登录</a></li>\r\n");
      out.write("\t\t\t\t");

            }
            else
            {
            	
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"DL_name\" onclick=\"javascript:alert('暂时不能提供查看个人信息')\">欢迎您:");
      out.print(name );
      out.write("</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"exit()\" class=\"DL_E\">退出</a></li>\r\n");
      out.write("\t\t\t\t");

            }
            
             
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function exit()\r\n");
      out.write("{\r\n");
      out.write("\tvar form = document.myform;\r\n");
      out.write("\t\tform.action=\"ExitServlet\";\r\n");
      out.write("\t\tform.method=\"post\";\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t<!--登录框-->\r\n");
      out.write("\t<div id=\"entry_box\">\r\n");
      out.write("\t\t<div class=\"dl_box\">\r\n");
      out.write("\t\t\t<div id=\"entry\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t<span id=\"entry_span1\" onClick=\"entryOne()\">请输入用户名</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span3\"></span><span id=\"entry_span3_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"entry_one\" name=\"username\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entryOne()\" onBlur=\"text()\" /><br /> <br /> <br /> <span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span2\" onClick=\"entry_one1()\">请输入登陆密码</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span4\"></span><span id=\"entry_span4_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"entry_two\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entry_one1()\" onBlur=\"text1()\" /><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"GO>>\" id=\"entry_submit\" onClick=\"decision()\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <span><a href=\"javascript:alert('正在全力建设')\"\r\n");
      out.write("\t\t\t\tclass=\"entry_span_1\">忘记密码&gt;&gt;</a></span>  --><span><a\r\n");
      out.write("\t\t\t\thref=\"html/l_zhuce.jsp\" class=\"entry_span_2\">注册&gt;&gt;</a></span>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"helpbox\">\r\n");
      out.write("\t\t<div class=\"helpboxL\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"helplli1\">\r\n");
      out.write("\t\t\t\t\t<h2>学生</h2> <a href=\"javascript:viod(0)\" class=\"now\">课程报名</a> <a href=\"javascript:viod(0)\">课前准备须知</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:viod(0)\">支付与退款</a> <a href=\"javascript:viod(0)\">常见问题</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"helplli2\">\r\n");
      out.write("\t\t\t\t\t<h2 id=\"teacher\">老师</h2> <a href=\"javascript:viod(0)\">课前准备须知</a> <a href=\"javascript:viod(0)\">上课说明</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"helplli3\">\r\n");
      out.write("\t\t\t\t\t<h2 id=\"company\">机构</h2> <a href=\"javascript:viod(0)\">机构入驻</a> <a href=\"javascript:viod(0)\">协议签署流程</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:viod(0)\">机构与群主签约</a> <a href=\"javascript:viod(0)\">机构与老师签约</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"helpboxR\">\r\n");
      out.write("\t\t\t<div class=\"helpboxR2\">\r\n");
      out.write("\t\t\t\t<h1>课程报名</h1>\r\n");
      out.write("\t\t\t\t<h3>1.怎么报名课程？</h3>\r\n");
      out.write("\t\t\t\t<p>在课程详情页，若该课程可报名，则点击报名进入报名流程。</p>\r\n");
      out.write("\t\t\t\t<h3>2.报名后课程怎么上课？</h3>\r\n");
      out.write("\t\t\t\t<p>a）通过QQ tips/QQ主面板上的课程入口进入。</p>\r\n");
      out.write("\t\t\t\t<p>b）通过群应用tab页机构正在上的课程点击\"立即上课\"进入。</p>\r\n");
      out.write("\t\t\t\t<p>c）通过课程平台\"我的课程\"中正在直播课程点击\"立即上课\"进入。</p>\r\n");
      out.write("\t\t\t\t<h3>3.报名课程可以退款吗？</h3>\r\n");
      out.write("\t\t\t\t<p>a）理论上课程开课之前都可以无条件退款。但系统拒绝恶意的付款退款行为 。</p>\r\n");
      out.write("\t\t\t\t<p>b）课程开始后课程便不允许退款了。可与机构协商退款事项。</p>\r\n");
      out.write("\t\t\t\t<h3>4.课程报名后可以取消报名吗？</h3>\r\n");
      out.write("\t\t\t\t<p>a）免费课程可在报名前取消报名。课程开始后不允许取消报名。</p>\r\n");
      out.write("\t\t\t\t<p>b）在我的课程页面，找到想要取消的课程，点击取消报名。</p>\r\n");
      out.write("\t\t\t\t<h3>5.什么是课时？</h3>\r\n");
      out.write("\t\t\t\t<p>该课程一共上几次课，当前时间是第几节课的安排。例如： \"第4节，共10节\"，表示当前课程是整个课程的第4节。</p>\r\n");
      out.write("\t\t\t\t<h3>6.什么是课表？ 课程表？</h3>\r\n");
      out.write("\t\t\t\t<p>KLEE课堂将您需要关注的上课信息整理成表，称课程表。其中的课程内容均为您已成功报名，并尚未开始的课程。</p>\r\n");
      out.write("\t\t\t\t<h3>7.什么是已报名课程？ 课程报名记录？</h3>\r\n");
      out.write("\t\t\t\t<p>课程报名记录记录了您在KLEE课堂平台上，所有有过报名行为课程的列表。部分课程已经报名成功，部分课程由于种种原因尚未报名成功，需要您进行继续操作。\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 版权部分修改版 -->\r\n");
      out.write("\t<div class=\"bottom_banquan\">\r\n");
      out.write("\t\t<div class=\"bottom_bg_color\">\r\n");
      out.write("\t\t\t<div class=\"bottom_box\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"lianxi_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bottom_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon1.png\" class=\"lianxi_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:viod(0)\" title=\"中国陕西省西安市长安区下北良村西安科技大学高新学院\">中国陕西省西安市长安区下北良村西安科技大学高新学院</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon3.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"tel:15596885995\" title=\"400-888-8888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">400-888-8888</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon2.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;margin-top:-8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"mailto:603049583@qq.com\" title=\"klee@163.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">klee@163.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--留言板  -->\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_right\">\r\n");
      out.write("\t\t\t\t\t<form onsubmit=\"tijiao()\" name=\"from_bus\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bottom_lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">邮&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"position:relative;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"youxiang(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"youxiang_box\" id=\"youxiang_\">邮箱格式有误</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang2\" name=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\" width=\"80px\" valign=\"top\">留言内容:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"kong\" cols=\"30\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang3\" style=\"resize:none;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><div class=\"lianxi_right_tijiao\" onclick=\"liuyan()\">Submit</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom_banquan_bq\">\r\n");
      out.write("\t\t\t<div class=\"bottom_banquan_center\">\r\n");
      out.write("\t\t\t\t<div class=\"banquan_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"banquan_bufen\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">Copyright © 2015 xike2-3zu. All RightsReserved.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">西科软件开发二班第三组 版权所有 | 贾国瑞 | 罗文杰 | 叶博武 | 付秀鹏</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--浮动猫链接-->\r\n");
      out.write("\t<div class=\"float_box\">\r\n");
      out.write("\t\t<div class=\"float\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"float_a\">返回顶部 <span class=\"float_bg\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"float1\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"float_a1\">关注微信 <span\r\n");
      out.write("\t\t\t\tclass=\"float_bg1\"></span> <img src=\"images/wx.JPG\" width=\"150\"\r\n");
      out.write("\t\t\t\theight=\"150\" class=\"weixin\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
