package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class business_005fsystem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>业务体系</title>\r\n");
      out.write("<link type=\"image/x-icon\" rel=\"shortcut icon\" href=\"../favicon.ico\" />\r\n");
      out.write("<link href=\"../css/head_nav.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/head.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/entry.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body{font-size:100%;}\r\n");
      out.write(".kc_center_onr {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 185px;\r\n");
      out.write("\t\r\n");
      out.write("\tmargin: 20px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kc_kc {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\t\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\tcolor: #099FB0;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tborder-bottom:1px solid #6F7574;\r\n");
      out.write("}\r\n");
      out.write(".kc_lb{color:#0E5049;font-weight:bold;}\r\n");
      out.write("#kc_jx li{float:left;margin:5px 40px 5px 0px;padding:2px 10px;font-size:15px;}\r\n");
      out.write("#kc_jx li a{color:#000;font-size:15px;font-family:\"等线\";}\r\n");
      out.write(".kc_jingxuan_1,.kc_jingxuan_2,.kc_jingxuan_3{clear:both;}\r\n");
      out.write(".kc_rm{width:1200px;height:40px;background:linear-gradient(110deg,#106994,rgba(240,249,253,0.2));clear:both;}\r\n");
      out.write("#kc_zx,#kc_zr{width:60px;height:40px;line-height:40px;display:inline-block;text-align:center;}\r\n");
      out.write("#kc_zx{background:#3EBB1A;}\r\n");
      out.write("#kc_zx a,#kc_zr a{color:#FFF;}\r\n");
      out.write("#kc_zx a:hover{color:#EA2D2D;}\r\n");
      out.write("#kc_zr a:hover{color:#EA2D2D;}\r\n");
      out.write("/* 课程内容 */\r\n");
      out.write(".kc_nr{width:1200px;height:525px;margin:20px auto;}\r\n");
      out.write("#zx_sum{width:276px;height:255px;float:left;margin:0px 10px 0px 11px;overflow:hidden;}\r\n");
      out.write(".kc_box{width:276px;height:180px;float:left;overflow:hidden;}\r\n");
      out.write(".zx_img{width:276px;height:180px;margin:0px;}\r\n");
      out.write(".hr{width:1200px;background:#A6A9A5;height:1px;clear:both;margin:10px 0px;float:left;}\r\n");
      out.write(".zx_zhuti,.zx_beizhu{float:left;width:276px;height:25px;display:inline-block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;\r\n");
      out.write("}\r\n");
      out.write(".zx_zhuti a{color:#000;font-size:15px;}\r\n");
      out.write(".zx_zhuti a:hover{color:#186970;}\r\n");
      out.write(".zx_beizhu{color:#969995;font-size:14px;}\r\n");
      out.write(".zx_xxcd,.zx_xxrs{display:inline-block;font-size:14px;float:left;width:auto;height:20px;line-height:20px;}\r\n");
      out.write(".zx_xxrs{float:right;color:#696C68;}\r\n");
      out.write(".zx_xxcd{color:green;line-height:30px;}\r\n");
      out.write(".zx_rentou{width:20px;height:20px;}\r\n");
      out.write("/*课程切换  */\r\n");
      out.write(".kc_qiehuan{width:1200px; height:80px;margin:0px auto;position:relative;}\r\n");
      out.write(".kc_shuzi{width:150px;height:30px;position:absolute;top:50%;left:50%;margin-left:-75px;margin-top:-15px;}\r\n");
      out.write(".kc_shuzi_ul li{width:auto;height:30px;color:#696C68;cursor:pointer;float:left;margin-right:15px;text-align:center;line-height:30px;}\r\n");
      out.write(".kc_shuzi_ul li:hover{color:#47B123;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("/*全部课程li背景  */\r\n");
      out.write("function backgd(obj){\r\n");
      out.write("\t\r\n");
      out.write("\tobj.style.backgroundColor=\"#00CACA\";\r\n");
      out.write("\tobj.style.borderRadius=\"10px\";\r\n");
      out.write("}\r\n");
      out.write("function backgdC(obj){\r\n");
      out.write("\t\r\n");
      out.write("\tobj.style.backgroundColor=\"rgba(255,255,255,0)\";\r\n");
      out.write("}\r\n");
      out.write("/*课程内容图片放大  */\r\n");
      out.write("  function imgFD(obj){\r\n");
      out.write("\t  obj.style.width=\"310px\";\r\n");
      out.write("\tobj.style.height=\"220px\";\r\n");
      out.write("\tobj.style.margin=\"-20px \";\r\n");
      out.write("\t obj.style.transition=\"all 300ms ease\";\r\n");
      out.write("\t}\r\n");
      out.write("  function imgSX(obj){\r\n");
      out.write("\t  obj.style.width=\"276px\";\r\n");
      out.write("\tobj.style.height=\"180px\";\r\n");
      out.write("\tobj.style.margin=\"0px\";\r\n");
      out.write("\t obj.style.transition=\"all 300ms ease\";\r\n");
      out.write("\t}\r\n");
      out.write(" /*课程切换  */\r\n");
      out.write(" function kcQH_one(){\r\n");
      out.write("\tdocument.getElementById(\"kc_zx\").style.backgroundColor=\"#3EBB1A\";\r\n");
      out.write("\tdocument.getElementById(\"kc_zr\").style.backgroundColor=\"rgba(0,0,0,0)\";\r\n");
      out.write("\t\r\n");
      out.write("\t document.getElementById(\"kcQH2\").style.display=\"none\";\r\n");
      out.write("\t document.getElementById(\"kcQH1\").style.display=\"block\";\r\n");
      out.write(" }\r\n");
      out.write(" function kcQH_two(){\r\n");
      out.write("\t document.getElementById(\"kc_zr\").style.backgroundColor=\"#3EBB1A\";\r\n");
      out.write("\t document.getElementById(\"kc_zx\").style.backgroundColor=\"rgba(0,0,0,0)\";\r\n");
      out.write("\t document.getElementById(\"kcQH2\").style.display=\"block\";\r\n");
      out.write("\t document.getElementById(\"kcQH1\").style.display=\"none\";\r\n");
      out.write(" }\r\n");
      out.write(" /*分页切换  */\r\n");
      out.write(" var tmp = 0;\r\n");
      out.write(" function kc_QhDiv1(){\r\n");
      out.write("\tif(document.getElementById(\"kcQH1\").style.display==\"block\"){\r\n");
      out.write("\t\t alert(\"这已经是首页哦\");\r\n");
      out.write("\t }\r\n");
      out.write("\t document.getElementById(\"kcQH2\").style.display=\"none\";\r\n");
      out.write("\t document.getElementById(\"kcQH1\").style.display=\"block\";\r\n");
      out.write("\t/* else{\r\n");
      out.write("\t\tdocument.getElementById(\"kcQH2\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"kcQH1\").style.display=\"block\";\r\n");
      out.write("\t } */\r\n");
      out.write(" }\r\n");
      out.write(" function kc_QhDiv2(){\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById(\"kcQH1\").style.display=\"none\";\r\n");
      out.write("\t\tif(document.getElementById(\"kcQH2\").style.display==\"block\"){\r\n");
      out.write("\t\t\t alert(\"这已经是尾页哦\");\r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"kcQH2\").style.display=\"block\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"kcQH1\").style.display=\"none\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--头部导航栏-->\r\n");
      out.write("\t<div id=\"head_nav\">\r\n");
      out.write("\t\t<div id=\"head_menu\">\r\n");
      out.write("\t\t\t<ul class=\"head_ul\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/logo3.png\" class=\"head_logo\" width=\"55\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/logo_4.png\" width=\"70\" class=\"head_logo_1\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"../images/faith.png\" class=\"head_logo1\" /></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"../index.jsp\" class=\"head_li\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"head_li\" id=\"head_li_from\"><a\r\n");
      out.write("\t\t\t\t\thref=\"business_system.jsp\" class=\"head_font_size\" style=\"color:#188eee;font-weight:bold;\">课程体系</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"head_nav_nav_none\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"yewu.html\" class=\"head_font_size\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"head_nav_yw_tx\" class=\"head_li\">业务体系</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"step_in.jsp\" class=\"head_li\">走进KLEE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"time_axis.jsp\" class=\"head_li\">发展历程</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/developer.jsp\" class=\"head_li\">论坛.活动</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"bangzhu.jsp\" class=\"head_li\">帮助</a></li>\r\n");
      out.write("\t\t\t\t");

					String name = (String) session.getAttribute("name");
					if (name == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"html/l_zhuce.jsp\" class=\"DL_zc\">注册</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"entry()\" class=\"DL_\">登录</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"DL_name\" onclick=\"javascript:alert('暂时不能提供查看个人信息')\">欢迎您:");
      out.print(name);
      out.write("</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"exit()\" class=\"DL_E\">退出</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--登录框-->\r\n");
      out.write("\t<div id=\"entry_box\">\r\n");
      out.write("\t\t<div class=\"dl_box\">\r\n");
      out.write("\t\t\t<div id=\"entry\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t<span id=\"entry_span1\" onClick=\"entryOne()\">请输入用户名</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span3\"></span><span id=\"entry_span3_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"entry_one\" name=\"username\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entryOne()\" onBlur=\"text()\" /><br /> <br /> <br /> <span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span2\" onClick=\"entry_one1()\">请输入登陆密码</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span4\"></span><span id=\"entry_span4_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"entry_two\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entry_one1()\" onBlur=\"text1()\" /><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"GO>>\" id=\"entry_submit\" onClick=\"decision()\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <span><a href=\"javascript:alert('正在全力建设')\"\r\n");
      out.write("\t\t\t\tclass=\"entry_span_1\">忘记密码&gt;&gt;</a></span> --> <span><a\r\n");
      out.write("\t\t\t\thref=\"l_zhuce.jsp\" class=\"entry_span_2\">注册&gt;&gt;</a></span>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--课程体系  -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"kc_center_onr\">\r\n");
      out.write("\t\t<div class=\"kc_kc\">全部课程</div>\r\n");
      out.write("\t\t<ul class=\"kc_jingxuan_1\" id=\"kc_jx\">\r\n");
      out.write("\t\t\t<li class=\"kc_lb\">方向:</li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">全部</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">前端开发(1)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">后端开发(3)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">ExMobi开发(5)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">原生移动开发(2)</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"kc_jingxuan_2\" id=\"kc_jx\">\r\n");
      out.write("\t\t\t<li class=\"kc_lb\">分类:</li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">全部</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">html5(1)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">jsp(3)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">css(5)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">ExMobi(2)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">ExMobi实战(6)</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">ExMobi扩展(6)</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"kc_jingxuan_3\" id=\"kc_jx\">\r\n");
      out.write("\t\t\t<li class=\"kc_lb\">难度:</li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">全部</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">初级</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">中级</a></li>\r\n");
      out.write("\t\t\t<li onmouseover=\"backgd(this)\" onmouseout=\"backgdC(this)\"><a href=\"javascript:alert('正在建设')\">高级</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"kc_rm\">\r\n");
      out.write("\t\t\t<span id=\"kc_zx\" onClick=\"kcQH_one()\"><a href=\"javascript:void(0)\">最新</a></span>\r\n");
      out.write("\t\t\t<span id=\"kc_zr\" onClick=\"kcQH_two()\"><a href=\"javascript:void(0)\">热门</a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--课程内容1  -->\r\n");
      out.write("\t<div class=\"kc_nr\" id=\"kcQH1\" style=\"display:block;\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<!-- 一区 -->\r\n");
      out.write("\t\t\t<li class=\"zx_yi\" id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a1.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 二区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a2.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 三区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a3.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 四区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a4.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"hr\"></li>\r\n");
      out.write("\t\t\t<!-- 五区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a5.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 六区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a6.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 七区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a7.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 八区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/a8.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"MongoDB集群之分片技术应用及其项目实战\">MongoDB集群之分片技术应用及其项目实战</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\">深入接触MongoDB集群分片技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">100人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"hr\"></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--课程内容2  -->\r\n");
      out.write("\t<div class=\"kc_nr\" id=\"kcQH2\" style=\"display:none;\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<!-- 一区 -->\r\n");
      out.write("\t\t\t<li class=\"zx_yi\" id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g10.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 二区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g9.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 三区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g8.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 四区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g7.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"hr\"></li>\r\n");
      out.write("\t\t\t<!-- 五区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g6.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 六区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g5.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 七区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g4.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<!-- 八区 -->\r\n");
      out.write("\t\t\t<li id=\"zx_sum\">\r\n");
      out.write("\t\t\t\t<div class=\"kc_box\"><img src=\"images/g3.jpg\" class=\"zx_img\" onmouseover=\"imgFD(this)\" onmouseout=\"imgSX(this)\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_zhuti\"><a href=\"javascript:alert('等会')\" title=\"【精品课】实战、PS入门到精通技术\">【精品课】实战、PS入门到精通技术,真正的零基础课程</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"zx_beizhu\" >PS入门到精通技术</div>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxcd\">未学习</span>\r\n");
      out.write("\t\t\t\t<span class=\"zx_xxrs\"><img src=\"images/ren.png\" class=\"zx_rentou\">200人学习</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"hr\"></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"kc_qiehuan\">\r\n");
      out.write("\t\t<div class=\"kc_shuzi\">\r\n");
      out.write("\t\t\t<ul class=kc_shuzi_ul>\r\n");
      out.write("\t\t\t\t<li onclick=\"kc_QhDiv1()\">上一页</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"kc_QhDiv2()\">下一页</li>\r\n");
      out.write("\t\t\t\t<!--<li><a href=\"javascript:alert('等会')\" >首页</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"javascript:alert('等会')\" >&nbsp;1&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:alert('等会')\" >&nbsp;2&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:alert('等会')\" >&nbsp;3&nbsp;</a></li> \r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:alert('等会')\" >尾页</a></li>-->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 版权部分修改版 -->\r\n");
      out.write("\t<div class=\"bottom_banquan\">\r\n");
      out.write("\t\t<div class=\"bottom_bg_color\">\r\n");
      out.write("\t\t\t<div class=\"bottom_box\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"lianxi_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bottom_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon1.png\" class=\"lianxi_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:viod(0)\" title=\"中国陕西省西安市长安区下北良村西安科技大学高新学院\">中国陕西省西安市长安区下北良村西安科技大学高新学院</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon3.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"tel:15596885995\" title=\"400-888-8888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">400-888-8888</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon2.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;margin-top:-8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"mailto:603049583@qq.com\" title=\"klee@163.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">klee@163.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--留言板  -->\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_right\">\r\n");
      out.write("\t\t\t\t\t<form onsubmit=\"tijiao()\" name=\"from_bus\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"10\" border=\"0\"  Width=\"100%\" class=\"bottom_lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">邮&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"position:relative;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"youxiang(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"youxiang_box\" id=\"youxiang_\">邮箱格式有误</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang2\" name=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\" width=\"80px\" valign=\"top\">留言内容:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"kong\" cols=\"30\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang3\" style=\"resize:none;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><div class=\"lianxi_right_tijiao\" onclick=\"liuyan()\">Submit</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom_banquan_bq\">\r\n");
      out.write("\t\t\t<div class=\"bottom_banquan_center\">\r\n");
      out.write("\t\t\t\t<div class=\"banquan_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"banquan_bufen\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">Copyright © 2015 xike2-3zu. All RightsReserved.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">西科软件开发二班第三组 版权所有 | 贾国瑞 | 罗文杰 | 叶博武 | 付秀鹏</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--浮动猫链接-->\r\n");
      out.write("\t<div class=\"float_box\">\r\n");
      out.write("\t\t<div class=\"float\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"float_a\">返回顶部 <span class=\"float_bg\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"float1\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"float_a1\">关注微信 <span\r\n");
      out.write("\t\t\t\tclass=\"float_bg1\"></span> <img src=\"images/wx.JPG\" width=\"150\"\r\n");
      out.write("\t\t\t\theight=\"150\" class=\"weixin\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
