package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class developer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<title>活动</title>\r\n");
      out.write("<link type=\"image/x-icon\" rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("<link href=\"css/head_nav.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/head.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/entry.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("#divMain {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\t/* background-color: #F00; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenter {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterImg {\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterButtonLeftDiv {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tmargin-top: -15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterButtonRightDiv {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tmargin-top: -15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterButtonLeft {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tborder: solid 2px #0099CC;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterButtonRight {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tborder: solid 2px #0099CC;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterNume {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tbottom: 30px;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tmargin-left: -60px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divCenterNume1,#divCenterNume2,#divCenterNume3,#divCenterNume4,#divCenterNume5\r\n");
      out.write("\t{\r\n");
      out.write("\twidth: 15px;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tline-height: 28px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".luntan_img {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("\theight: 110px;\r\n");
      out.write("\tpadding-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".luntan_box {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 350px;\r\n");
      out.write("\tmargin: 20px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".luntan_title {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tborder-bottom: 1px solid #B6B3B1;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".luntan_center1,.luntan_center2,.luntan_center3 {\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("\t/*border: 1px solid red;*/\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".luntan_center4 {\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("\tpadding-left: 20px; /*border: 1px solid red;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fontsize {\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#div li {\r\n");
      out.write("\tlist-style: disc;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar nume = 1;\r\n");
      out.write("\tvar color = [ \"#271F37\", \"#000000\", \"#EDDCE6\", \"#BFDF96\", \"#D97EDD\" ];\r\n");
      out.write("\tfunction run() {\r\n");
      out.write("\t\tif (nume > 5) {\r\n");
      out.write("\t\t\tnume = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\timgRun(nume);\r\n");
      out.write("\t\tnume++;\r\n");
      out.write("\t\tstop1 = setTimeout(\"run()\", 2000);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction imgRun(nume1) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (nume1 > 2) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"divCenterImg\").style.margin = \"0px 25%\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.getElementById(\"divCenterImg\").style.margin = \"0px auto\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"divCenterImg\").src = \"html/images/luntan\"\r\n");
      out.write("\t\t\t\t+ nume1 + \".jpg\";\r\n");
      out.write("\t\tfor (var i = 1; i <= 5; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"divCenterNume\" + i).style.backgroundColor = \"white\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"divCenterNume\" + nume1).style.backgroundColor = \"red\";\r\n");
      out.write("\t\tcolor1 = color[nume1 - 1];\r\n");
      out.write("\t\tdocument.getElementById(\"divMain\").style.backgroundColor = color1;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction stop3() {\r\n");
      out.write("\t\tclearTimeout(stop1);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction stop2(shu) {\r\n");
      out.write("\r\n");
      out.write("\t\tnume = shu;\r\n");
      out.write("\t\timgRun(nume);\r\n");
      out.write("\t\tstop3();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction buttonRight() {\r\n");
      out.write("\t\tnume = nume + 1;\r\n");
      out.write("\t\tif (nume > 5) {\r\n");
      out.write("\t\t\tnume = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\timgRun(nume);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction buttonLeft() {\r\n");
      out.write("\t\tnume = nume - 1;\r\n");
      out.write("\t\tif (nume < 1) {\r\n");
      out.write("\t\t\tnume = 5;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\timgRun(nume);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- onLoad=\"Load_one()\" -->\r\n");
      out.write("<body style=\"background:#fff;\" onload=\"run()\">\r\n");
      out.write("\t<!--头部导航栏-->\r\n");
      out.write("\t<div id=\"head_nav\">\r\n");
      out.write("\t\t<div id=\"head_menu\">\r\n");
      out.write("\t\t\t<ul class=\"head_ul\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/logo3.png\" class=\"head_logo\" width=\"55\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/logo_4.png\" width=\"70\" class=\"head_logo_1\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/faith.png\" class=\"head_logo1\" /></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\" class=\"head_li\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"head_li\" id=\"head_li_from\"><a\r\n");
      out.write("\t\t\t\t\thref=\"html/business_system.jsp\" class=\"head_font_size\">课程体系</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"head_nav_nav_none\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"html/yewu.html\" class=\"head_font_size\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"head_nav_yw_tx\" class=\"head_li\">业务体系</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/step_in.jsp\" class=\"head_li\">走进KLEE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/time_axis.jsp\" class=\"head_li\">发展历程</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/developer.jsp\" class=\"head_li\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color:#09C;font-weight:bold;\">论坛.活动</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/bangzhu.jsp\" class=\"head_li\">帮助</a></li>\r\n");
      out.write("\t\t\t\t");

					String name = (String) session.getAttribute("name");
					if (name == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"html/l_zhuce.jsp\" class=\"DL_zc\">注册</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"entry()\" class=\"DL_\">登录</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"DL_name\" onclick=\"javascript:alert('暂时不能提供查看个人信息')\">欢迎您:");
      out.print(name);
      out.write("</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"exit()\" class=\"DL_E\">退出</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--登录框-->\r\n");
      out.write("\t<div id=\"entry_box\">\r\n");
      out.write("\t\t<div class=\"dl_box\">\r\n");
      out.write("\t\t\t<div id=\"entry\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t<span id=\"entry_span1\" onClick=\"entryOne()\">请输入用户名</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span3\"></span><span id=\"entry_span3_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"entry_one\" name=\"username\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entryOne()\" onBlur=\"text()\" /><br /> <br /> <br /> <span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span2\" onClick=\"entry_one1()\">请输入登陆密码</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span4\"></span><span id=\"entry_span4_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"entry_two\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entry_one1()\" onBlur=\"text1()\" /><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"GO>>\" id=\"entry_submit\" onClick=\"decision()\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <span><a href=\"javascript:alert('正在全力建设')\"\r\n");
      out.write("\t\t\t\tclass=\"entry_span_1\">忘记密码&gt;&gt;</a></span> --> <span><a\r\n");
      out.write("\t\t\t\thref=\"html/l_zhuce.jsp\" class=\"entry_span_2\">注册&gt;&gt;</a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--幻灯片区  -->\r\n");
      out.write("\t<div id=\"divMain\">\r\n");
      out.write("\t\t<div id=\"divLeft\"></div>\r\n");
      out.write("\t\t<div id=\"divCenter\">\r\n");
      out.write("\t\t\t<div id=\"divCenterButtonLeftDiv\" onmouseover=\"stop3()\"\r\n");
      out.write("\t\t\t\tonmouseout=\"run()\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"buttonLeft()\" id=\"divCenterButtonLeft\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"divCenterButtonRightDiv\" onmouseover=\"stop3()\"\r\n");
      out.write("\t\t\t\tonmouseout=\"run()\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"buttonRight()\"\r\n");
      out.write("\t\t\t\t\tid=\"divCenterButtonRight\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img src=\"html/images/luntan1.jpg\" id=\"divCenterImg\" />\r\n");
      out.write("\t\t\t<div id=\"divCenterNume\">\r\n");
      out.write("\t\t\t\t<div id=\"divCenterNume1\" onmouseover=\"stop2(1)\" onmouseout=\"run()\">1</div>\r\n");
      out.write("\t\t\t\t<div id=\"divCenterNume2\" onmouseover=\"stop2(2)\" onmouseout=\"run()\">2</div>\r\n");
      out.write("\t\t\t\t<div id=\"divCenterNume3\" onmouseover=\"stop2(3)\" onmouseout=\"run()\">3</div>\r\n");
      out.write("\t\t\t\t<div id=\"divCenterNume4\" onmouseover=\"stop2(4)\" onmouseout=\"run()\">4</div>\r\n");
      out.write("\t\t\t\t<div id=\"divCenterNume5\" onmouseover=\"stop2(5)\" onmouseout=\"run()\">5</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"divRight\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  -->\r\n");
      out.write("\t<div class=\"luntan_box\">\r\n");
      out.write("\t\t<div class=\"luntan_title\">IT培训团</div>\r\n");
      out.write("\t\t<div class=\"luntan_center1\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z0.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">安卓开发团</li>\r\n");
      out.write("\t\t\t\t<li>最活跃的安卓开发交流区</li>\r\n");
      out.write("\t\t\t\t<li>团友数4121</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center2\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z4.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">PS大神养成团</li>\r\n");
      out.write("\t\t\t\t<li>所有喜爱绘画、设计、广告等等</li>\r\n");
      out.write("\t\t\t\t<li>团友数68274</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center3\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z3.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">网页平面设计团</li>\r\n");
      out.write("\t\t\t\t<li>欢迎平面设计控一起交流</li>\r\n");
      out.write("\t\t\t\t<li>团友数10495</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<ul id=\"div\">\r\n");
      out.write("\t\t\t\t<li>第十八天跟着大磨马学IT编程（安卓java）</li>\r\n");
      out.write("\t\t\t\t<li>十七天跟着大磨马学IT编程（安卓java程序员）</li>\r\n");
      out.write("\t\t\t\t<li>你们好，朋友们谁有反编译工具跟打包签名软件，分享下</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z2.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">室内建筑设计团</li>\r\n");
      out.write("\t\t\t\t<li>跟团友一起，一步步成为设计专家！</li>\r\n");
      out.write("\t\t\t\t<li>团友数13018</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z1.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">编程设计团</li>\r\n");
      out.write("\t\t\t\t<li>编程爱好集中地</li>\r\n");
      out.write("\t\t\t\t<li>团友数21551</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--内容区（总分四区） -->\r\n");
      out.write("\t<div class=\"luntan_box\">\r\n");
      out.write("\t\t<div class=\"luntan_title\">语言培训团</div>\r\n");
      out.write("\t\t<div class=\"luntan_center1\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z5.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">考研团</li>\r\n");
      out.write("\t\t\t\t<li>提供考研相关的资讯和公共课资料</li>\r\n");
      out.write("\t\t\t\t<li>团友数1243</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center2\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z6.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">英语团</li>\r\n");
      out.write("\t\t\t\t<li>每天坚持说英语，成为英语达人</li>\r\n");
      out.write("\t\t\t\t<li>团友数30683</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center3\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z7.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">日语团</li>\r\n");
      out.write("\t\t\t\t<li>日语综合学团，分享你的学习经验</li>\r\n");
      out.write("\t\t\t\t<li>团友数11474</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<ul id=\"div\">\r\n");
      out.write("\t\t\t\t<li>有机会实现梦想让人生变得有趣</li>\r\n");
      out.write("\t\t\t\t<li>2016考研时间及科目安排</li>\r\n");
      out.write("\t\t\t\t<li>2016考研冲刺：靠谱复习计划三大要素</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z8.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">韩语团</li>\r\n");
      out.write("\t\t\t\t<li>热爱韩语的小伙伴们，快来思密达！</li>\r\n");
      out.write("\t\t\t\t<li>团友数27238</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--内容区（总分四区） -->\r\n");
      out.write("\t<div class=\"luntan_box\">\r\n");
      out.write("\t\t<div class=\"luntan_title\">职业技能团</div>\r\n");
      out.write("\t\t<div class=\"luntan_center1\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z9.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">医师考试交流团</li>\r\n");
      out.write("\t\t\t\t<li>国家医师资格考试学习.交流.分享</li>\r\n");
      out.write("\t\t\t\t<li>团友数2258</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center2\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z10.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">公务员考试交流团</li>\r\n");
      out.write("\t\t\t\t<li>分享公务员考试.培训经验</li>\r\n");
      out.write("\t\t\t\t<li>团友数6031</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center3\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z11.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">会计学习团</li>\r\n");
      out.write("\t\t\t\t<li>欢迎学习会计有兴趣的同学加入</li>\r\n");
      out.write("\t\t\t\t<li>团友数11336</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<ul id=\"div\">\r\n");
      out.write("\t\t\t\t<li>百通老师提示：2016年护士资格考试大纲变化</li>\r\n");
      out.write("\t\t\t\t<li>2016年护士资格考试大纲变化及新旧对比图</li>\r\n");
      out.write("\t\t\t\t<li>2016年执业医师考试复习规划-“6段式备考策略”</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z12.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">求职创业团</li>\r\n");
      out.write("\t\t\t\t<li>面试经验.求职技巧.这里应有尽有！</li>\r\n");
      out.write("\t\t\t\t<li>团友数13219</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z13.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">应届求职团</li>\r\n");
      out.write("\t\t\t\t<li>应届生过来看.高薪就业</li>\r\n");
      out.write("\t\t\t\t<li>团友数4286</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--内容区（总分四区） -->\r\n");
      out.write("\t<div class=\"luntan_box\">\r\n");
      out.write("\t\t<div class=\"luntan_title\">兴趣爱好团</div>\r\n");
      out.write("\t\t<div class=\"luntan_center1\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z14.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">摄影团</li>\r\n");
      out.write("\t\t\t\t<li>一起分享生活中捕捉的美图</li>\r\n");
      out.write("\t\t\t\t<li>团友数13810</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center2\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z15.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">恋爱宝典分享团</li>\r\n");
      out.write("\t\t\t\t<li>如何追到心仪的妹子？</li>\r\n");
      out.write("\t\t\t\t<li>团友数15994</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center3\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z16.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">投资理财团</li>\r\n");
      out.write("\t\t\t\t<li>学习理财知识，分享理财心得</li>\r\n");
      out.write("\t\t\t\t<li>团友数12288</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<ul id=\"div\">\r\n");
      out.write("\t\t\t\t<li>雪域高原</li>\r\n");
      out.write("\t\t\t\t<li>你约吗？</li>\r\n");
      out.write("\t\t\t\t<li>人间喜剧</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z17.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">一起唱歌团</li>\r\n");
      out.write("\t\t\t\t<li>show出你的歌唱技巧</li>\r\n");
      out.write("\t\t\t\t<li>团友数8321</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"luntan_center4\">\r\n");
      out.write("\t\t\t<img src=\"html/images/z18.jpg\" class=\"luntan_img\" />\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"fontsize\">1758一起舞吧团</li>\r\n");
      out.write("\t\t\t\t<li>每一次翩翩起舞的背后</li>\r\n");
      out.write("\t\t\t\t<li>团友数12630</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 版权部分修改版 -->\r\n");
      out.write("\t<div class=\"bottom_banquan\">\r\n");
      out.write("\t\t<div class=\"bottom_bg_color\">\r\n");
      out.write("\t\t\t<div class=\"bottom_box\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"lianxi_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bottom_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon1.png\" class=\"lianxi_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:viod(0)\" title=\"中国陕西省西安市长安区下北良村西安科技大学高新学院\">中国陕西省西安市长安区下北良村西安科技大学高新学院</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon3.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"tel:15596885995\" title=\"400-888-8888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">400-888-8888</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon2.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;margin-top:-8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"mailto:603049583@qq.com\" title=\"klee@163.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">klee@163.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--留言板  -->\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_right\">\r\n");
      out.write("\t\t\t\t\t<form onsubmit=\"tijiao()\" name=\"from_bus\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bottom_lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">邮&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"position:relative;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"youxiang(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"youxiang_box\" id=\"youxiang_\">邮箱格式有误</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang2\" name=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\" width=\"80px\" valign=\"top\">留言内容:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"kong\" cols=\"30\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang3\" style=\"resize:none;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><div class=\"lianxi_right_tijiao\" onclick=\"liuyan()\">Submit</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom_banquan_bq\">\r\n");
      out.write("\t\t\t<div class=\"bottom_banquan_center\">\r\n");
      out.write("\t\t\t\t<div class=\"banquan_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"banquan_bufen\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">Copyright © 2015 xike2-3zu. All RightsReserved.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">西科软件开发二班第三组 版权所有 | 贾国瑞 | 罗文杰 | 叶博武 | 付秀鹏</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--浮动猫链接-->\r\n");
      out.write("\t<div class=\"float_box\">\r\n");
      out.write("\t\t<div class=\"float\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"float_a\">返回顶部 <span class=\"float_bg\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"float1\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"float_a1\">关注微信 <span\r\n");
      out.write("\t\t\t\tclass=\"float_bg1\"></span> <img src=\"images/wx.JPG\" width=\"150\"\r\n");
      out.write("\t\t\t\theight=\"150\" class=\"weixin\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
