package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class step_005fin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<title>走进KLEE</title>\r\n");
      out.write("<link type=\"image/x-icon\" rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("<link href=\"css/head_nav.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/head.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/entry.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".step_center {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tbackground: url(html/images/bgheader.jpg);\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_xy,.step_xy_one,.step_xy_two {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\twidth: 450px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_xy {\r\n");
      out.write("\tfont-size: 32px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-family: \"楷体\";\r\n");
      out.write("\tmargin: -80px 0px 0px -225px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_xy_one {\r\n");
      out.write("\tfont-size: 19px;\r\n");
      out.write("\tcolor: #CCCCCC;\r\n");
      out.write("\tmargin: -10px 0px 0px -225px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_xy_two {\r\n");
      out.write("\tfont-size: 29px;\r\n");
      out.write("\tcolor: #0080C0;\r\n");
      out.write("\tmargin: 50px 0px 0px -225px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_bg_gd {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tbackground: linear-gradient(to right, rgba(13, 94, 80, 1),\r\n");
      out.write("\t\trgba(13, 94, 80, 0.1));\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: -40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#step_font1,#step_font2,#step_font3,#step_font4 {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tletter-spacing: 30px;\r\n");
      out.write("}\r\n");
      out.write("/*企业精神  */\r\n");
      out.write(".step_center_C {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 302px;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_qyjs {\r\n");
      out.write("\twidth: 807px;\r\n");
      out.write("\theight: 302px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qyjs_one {\r\n");
      out.write("\twidth: 301px;\r\n");
      out.write("\theight: 208px;\r\n");
      out.write("\tbackground: url(html/images/3.png);\r\n");
      out.write("\tbackground-size: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qyjs_two {\r\n");
      out.write("\twidth: 249px;\r\n");
      out.write("\theight: 309px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground: url(html/images/1.png);\r\n");
      out.write("\tbackground-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qyjs_three {\r\n");
      out.write("\twidth: 257px;\r\n");
      out.write("\theight: 208px;\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tbackground: url(html/images/2.png);\r\n");
      out.write("\tbackground-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_hzqy_bg {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 280px;\r\n");
      out.write("\tbackground: #FFF;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_hzqy {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 250px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hzqy_img {\r\n");
      out.write("\twidth: 330px;\r\n");
      out.write("\theight: 260px;\r\n");
      out.write("\tbackground: url(html/images/dl12.jpg);\r\n");
      out.write("\tbackground-size: 300px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hzqy_jieshao,.mb_font {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tfont-family: \"YaHei Consolas Hybrid\";\r\n");
      out.write("\t\r\n");
      out.write("\ttext-indent: 3em;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\tletter-spacing: 7px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tcolor: #30332F;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hzqy_jieshao {\r\n");
      out.write("\twidth: 860px;\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("/*教育目标  */\r\n");
      out.write(".step_mb {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 350px;\r\n");
      out.write("\tmargin: 20px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step_mb img {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb_font {\r\n");
      out.write("\twidth: 790px;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("/*底层介绍  */\r\n");
      out.write(".step_kjzf {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kjzf_one,.kjzf_two,.kjzf_three {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kjzf_img {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kjzf_nav {\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kjzf_lan {\r\n");
      out.write("\tmargin-left: -20px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".li_img1 {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tbackground: url(html/images/thumb.png);\r\n");
      out.write("\tbackground-size: 20px 20px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".li_img {\r\n");
      out.write("\twidth: 16px;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("\tbackground: url(html/images/li.png);\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kjzf_nav_lan li {\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction color() {\r\n");
      out.write("\t\tvar fontColor = parseInt(Math.random() * 10000);\r\n");
      out.write("\t\tvar a = document.getElementById(\"step_font1\");\r\n");
      out.write("\t\tvar b = document.getElementById(\"step_font2\");\r\n");
      out.write("\t\tvar c = document.getElementById(\"step_font3\");\r\n");
      out.write("\t\tvar d = document.getElementById(\"step_font4\");\r\n");
      out.write("\t\ta.style.color = \"#bc\" + fontColor;\r\n");
      out.write("\t\ta.style.letterSpacing = \"0px\";\r\n");
      out.write("\t\ta.style.transition = \"all 2s ease\";\r\n");
      out.write("\t\tb.style.letterSpacing = \"0px\";\r\n");
      out.write("\t\tb.style.transition = \"all 1s ease\";\r\n");
      out.write("\t\tb.style.color = \"#b\" + fontColor + \"c\";\r\n");
      out.write("\t\tc.style.color = \"#e\" + fontColor + \"a\";\r\n");
      out.write("\t\tc.style.letterSpacing = \"0px\";\r\n");
      out.write("\t\tc.style.transition = \"all 1s ease\";\r\n");
      out.write("\t\td.style.color = \"#e\" + fontColor + \"a\";\r\n");
      out.write("\t\td.style.letterSpacing = \"0px\";\r\n");
      out.write("\t\td.style.transition = \"all 1s ease\";\r\n");
      out.write("\t\tsetTimeout(color, 600);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"color()\">\r\n");
      out.write("\t<!--头部导航栏-->\r\n");
      out.write("\t<div id=\"head_nav\">\r\n");
      out.write("\t\t<div id=\"head_menu\">\r\n");
      out.write("\t\t\t<ul class=\"head_ul\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/logo3.png\" class=\"head_logo\" width=\"55\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/logo_4.png\" width=\"70\" class=\"head_logo_1\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/faith.png\" class=\"head_logo1\" /></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\" class=\"head_li\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"head_li\" id=\"head_li_from\"><a\r\n");
      out.write("\t\t\t\t\thref=\"html/business_system.jsp\" class=\"head_font_size\">课程体系</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"head_nav_nav_none\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"html/yewu.html\" class=\"head_font_size\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"head_nav_yw_tx\" class=\"head_li\">业务体系</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/step_in.jsp\" class=\"head_li\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color:#09C;font-weight:bold;\">走进KLEE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/time_axis.jsp\" class=\"head_li\">发展历程</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/developer.jsp\" class=\"head_li\">论坛.活动</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/bangzhu.jsp\" class=\"head_li\">帮助</a></li>\r\n");
      out.write("\t\t\t\t");

					String name = (String) session.getAttribute("name");
					if (name == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"html/l_zhuce.jsp\" class=\"DL_zc\">注册</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"entry()\" class=\"DL_\">登录</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"DL_name\" onclick=\"javascript:alert('暂时不能提供查看个人信息')\">欢迎您:");
      out.print(name);
      out.write("</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"exit()\" class=\"DL_E\">退出</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--登录框-->\r\n");
      out.write("\t<div id=\"entry_box\">\r\n");
      out.write("\t\t<div class=\"dl_box\">\r\n");
      out.write("\t\t\t<div id=\"entry\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t<span id=\"entry_span1\" onClick=\"entryOne()\">请输入用户名</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span3\"></span><span id=\"entry_span3_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"entry_one\" name=\"username\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entryOne()\" onBlur=\"text()\" /><br /> <br /> <br /> <span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span2\" onClick=\"entry_one1()\">请输入登陆密码</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span4\"></span><span id=\"entry_span4_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"entry_two\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entry_one1()\" onBlur=\"text1()\" /><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"GO>>\" id=\"entry_submit\" onClick=\"decision()\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <span><a href=\"javascript:alert('正在全力建设')\"\r\n");
      out.write("\t\t\t\tclass=\"entry_span_1\">忘记密码&gt;&gt;</a></span> --><span><a\r\n");
      out.write("\t\t\t\thref=\"html/l_zhuce.jsp\" class=\"entry_span_2\">注册&gt;&gt;</a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--背景区  -->\r\n");
      out.write("\t<div class=\"step_center\">\r\n");
      out.write("\t\t<div class=\"step_xy\">互联网最热门的在线教育学院</div>\r\n");
      out.write("\t\t<div class=\"step_xy_one\">2015.KLEE学院点亮你的梦想</div>\r\n");
      out.write("\t\t<div class=\"step_xy_two\">Welcome to our education</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"step_bg_gd\">\r\n");
      out.write("\t\t<div id=\"step_font1\">Spirit of enterprise</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 学院介绍 -->\r\n");
      out.write("\t<div class=\"step_center_C\">\r\n");
      out.write("\t\t<div class=\"step_qyjs\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"qyjs_one\"></li>\r\n");
      out.write("\t\t\t\t<li class=\"qyjs_two\"></li>\r\n");
      out.write("\t\t\t\t<li class=\"qyjs_three\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"step_bg_gd\"\r\n");
      out.write("\t\tstyle=\"top:0px;background: linear-gradient(to right, #1D2F30,\r\n");
      out.write("\t\t#659FA3);\">\r\n");
      out.write("\t\t<div id=\"step_font2\">Co-Operative Enterprise</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 合作企业 -->\r\n");
      out.write("\t<div class=\"step_hzqy_bg\">\r\n");
      out.write("\t\t<div class=\"step_hzqy\">\r\n");
      out.write("\t\t\t<div class=\"hzqy_img\"></div>\r\n");
      out.write("\t\t\t<div class=\"hzqy_jieshao\">KLEE人以服务社会、振兴中国软件产业为己任，励精图治，改革创新，开拓进取，经过二十余年拼搏，取得了令人瞩目的业绩。展望未来，公司将抓住机遇，加大自主产品创新，加快国际化进程，实现规模经济和跨越式发展，成为具有国际竞争力、国际知名度的中国软件旗舰企业，跻身世界软件企业百强，实现“中国软件第一品牌，世界一流知名企业”。</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"step_bg_gd\"\r\n");
      out.write("\t\tstyle=\"top:0px;background: linear-gradient(to right, #052341,\r\n");
      out.write("\t\t#2B8CEE);\">\r\n");
      out.write("\t\t<div id=\"step_font3\">Educational objective</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"step_mb\">\r\n");
      out.write("\t\t<div class=\"mb_font\">KLEE教育一直秉承“用良心做教育”的理念，是中国移动互联网研发人才一体化服务的领导品牌，\r\n");
      out.write("\t\t\t全力打造移动互联网高端研发人才服务平台。公司总部位于北京，目前已在深圳、上海、郑州、广州、大连、武汉、成都、西安、青岛、杭州成立了分公司。拥有全国最多、最权威的移动互联网教学就业保障团队，\r\n");
      out.write("\t\t\t做到了毕业学员业内最高薪水，成为学员最信赖的IT培训机构。千锋教育是中关村移动互联网产业联盟副理事长单位，\r\n");
      out.write("\t\t\t中国软件协会教育培训委员会认证首家一级培训机构，中关村国际孵化软件协会唯一授权中关村移动互联网学院，年培养学员数量20000人，\r\n");
      out.write("\t\t\t合作院校超500所，合作企业超4000家，APP上线项目超1000个，每年有数十万名学员受益于KLEE教育组织的技术研讨会、技术培训课、\r\n");
      out.write("\t\t\t网络公开课及免费教学视频</div>\r\n");
      out.write("\t\t<img src=\"html/images/mb.png\" height=\"350\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"step_bg_gd\"\r\n");
      out.write("\t\tstyle=\"top:0px;background: linear-gradient(to right, #11410A,\r\n");
      out.write("\t\t#2B8CEE);\">\r\n");
      out.write("\t\t<div id=\"step_font4\">Shortcut</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--快捷  -->\r\n");
      out.write("\t<div class=\"step_kjzf\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"kjzf_one\"><img src=\"html/images/dl_08.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"120\" class=\"kjzf_img\">\r\n");
      out.write("\t\t\t\t<div class=\"kjzf_nav\">\r\n");
      out.write("\t\t\t\t\t<span class=\"kjzf_lan\"><span class=\"li_img1\"></span>&nbsp;&nbsp;支持在线支付</span>\r\n");
      out.write("\t\t\t\t\t<ul class=\"kjzf_nav_lan\">\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;支付宝</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;财付通</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;银行卡</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"kjzf_two\"><img src=\"html/images/dl_06.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"120\" class=\"kjzf_img\">\r\n");
      out.write("\t\t\t\t<div class=\"kjzf_nav\">\r\n");
      out.write("\t\t\t\t\t<span class=\"kjzf_lan\"><span class=\"li_img1\"></span>&nbsp;&nbsp;支持在线支付</span>\r\n");
      out.write("\t\t\t\t\t<ul class=\"kjzf_nav_lan\">\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;支付宝</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;财付通</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;银行卡</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"kjzf_three\"><img src=\"html/images/dl_07.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"120\" class=\"kjzf_img\">\r\n");
      out.write("\t\t\t\t<div class=\"kjzf_nav\">\r\n");
      out.write("\t\t\t\t\t<span class=\"kjzf_lan\"><span class=\"li_img1\"></span>&nbsp;&nbsp;支持在线支付</span>\r\n");
      out.write("\t\t\t\t\t<ul class=\"kjzf_nav_lan\">\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;支付宝</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;财付通</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"li_img\"></span>&nbsp;&nbsp;银行卡</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 版权部分修改版 -->\r\n");
      out.write("\t<div class=\"bottom_banquan\">\r\n");
      out.write("\t\t<div class=\"bottom_bg_color\">\r\n");
      out.write("\t\t\t<div class=\"bottom_box\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"lianxi_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bottom_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon1.png\" class=\"lianxi_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:viod(0)\" title=\"中国陕西省西安市长安区下北良村西安科技大学高新学院\">中国陕西省西安市长安区下北良村西安科技大学高新学院</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon3.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"tel:15596885995\" title=\"400-888-8888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">400-888-8888</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon2.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;margin-top:-8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"mailto:603049583@qq.com\" title=\"klee@163.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">klee@163.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--留言板  -->\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_right\">\r\n");
      out.write("\t\t\t\t\t<form onsubmit=\"tijiao()\" name=\"from_bus\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bottom_lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">邮&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"position:relative;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"youxiang(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"youxiang_box\" id=\"youxiang_\">邮箱格式有误</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang2\" name=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\" width=\"80px\" valign=\"top\">留言内容:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"kong\" cols=\"30\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang3\" style=\"resize:none;\"></textarea><</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><div class=\"lianxi_right_tijiao\" onclick=\"liuyan()\">Submit</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom_banquan_bq\">\r\n");
      out.write("\t\t\t<div class=\"bottom_banquan_center\">\r\n");
      out.write("\t\t\t\t<div class=\"banquan_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"banquan_bufen\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">Copyright © 2015 xike2-3zu. All RightsReserved.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">西科软件开发二班第三组 版权所有 | 贾国瑞 | 罗文杰 | 叶博武 | 付秀鹏</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--浮动猫链接-->\r\n");
      out.write("\t<div class=\"float_box\">\r\n");
      out.write("\t\t<div class=\"float\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"float_a\">返回顶部 <span class=\"float_bg\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"float1\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"float_a1\">关注微信 <span\r\n");
      out.write("\t\t\t\tclass=\"float_bg1\"></span> <img src=\"images/wx.JPG\" width=\"150\"\r\n");
      out.write("\t\t\t\theight=\"150\" class=\"weixin\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
