package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class time_005faxis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<title>发展历程</title>\r\n");
      out.write("<link type=\"image/x-icon\" rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/head_nav.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/head.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/entry.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: \"微软雅黑\";\r\n");
      out.write("\tbackground: #EFEFEF;\r\n");
      out.write("\t/* background:#081130 url(html/images/bg.jpg) repeat;background-size:100% 900px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divyuan {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 142px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\twidth: 130px;\r\n");
      out.write("\theight: 130px;\r\n");
      out.write("\tborder-radius: 100px;\r\n");
      out.write("\tbackground: url(html/images/time.png);\r\n");
      out.write("\tbackground-size: 130px;\r\n");
      out.write("\tcolor: #686868;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 130px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tborder: 5px #0C47B6 solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divshugang {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 210px;\r\n");
      out.write("\ttop: 150px;\r\n");
      out.write("\twidth: 5px;\r\n");
      out.write("\theight: 590px;\r\n");
      out.write("\tbackground-color: rgba(6, 106, 255, 0.7);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian1,.divdian2,.divdian3,.divdian4,.divdian5,.divdian6 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 203px;\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("\tbackground-color: rgba(6, 106, 255, 1);\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian1 {\r\n");
      out.write("\ttop: 220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian2 {\r\n");
      out.write("\ttop: 320px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian3 {\r\n");
      out.write("\ttop: 420px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian4 {\r\n");
      out.write("\ttop: 520px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian5 {\r\n");
      out.write("\ttop: 620px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divdian6 {\r\n");
      out.write("\ttop: 720px;\r\n");
      out.write("\tbackground-color: rgba(213, 69, 0, 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang1,.divkuang2,.divkuang3,.divkuang4,.divkuang5,.divkuang6 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 270px;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground-color: rgba(102, 120, 242, 0.6);;\r\n");
      out.write("\ttransition: width 100ms sease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang1 {\r\n");
      out.write("\ttop: 220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang1:hover {\r\n");
      out.write("\twidth: 620px;\r\n");
      out.write("\theight: 62px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttransition: width 100ms ease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang2 {\r\n");
      out.write("\ttop: 320px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang2:hover {\r\n");
      out.write("\twidth: 620px;\r\n");
      out.write("\theight: 62px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttransition: width 100ms ease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang3 {\r\n");
      out.write("\ttop: 420px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang3:hover {\r\n");
      out.write("\twidth: 620px;\r\n");
      out.write("\theight: 62px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttransition: width 100ms ease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang4 {\r\n");
      out.write("\ttop: 520px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang4:hover {\r\n");
      out.write("\twidth: 620px;\r\n");
      out.write("\theight: 62px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttransition: width 100ms ease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang5 {\r\n");
      out.write("\ttop: 620px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang5:hover {\r\n");
      out.write("\twwidth: 620px;\r\n");
      out.write("\theight: 62px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttransition: width 100ms ease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang6 {\r\n");
      out.write("\ttop: 720px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divkuang6:hover {\r\n");
      out.write("\twwidth: 620px;\r\n");
      out.write("\theight: 62px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttransition: width 100ms ease-in, height 100ms ease-in, font-size 100ms\r\n");
      out.write("\t\tease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divbiao {\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #9D6A37;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 400px;\r\n");
      out.write("\tfont-family: \"楷体\";\r\n");
      out.write("\ttop: 80px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi1,.divzi2,.divzi3,.divzi4,.divzi5,.divzi6 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 100px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tcolor: #8D6C34;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi1 {\r\n");
      out.write("\ttop: 215px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi2 {\r\n");
      out.write("\ttop: 315px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi3 {\r\n");
      out.write("\ttop: 415px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi4 {\r\n");
      out.write("\ttop: 515px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi5 {\r\n");
      out.write("\ttop: 615px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divzi6 {\r\n");
      out.write("\ttop: 715px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"headNav()\">\r\n");
      out.write("\t<!--头部导航栏-->\r\n");
      out.write("\t<div id=\"head_nav\">\r\n");
      out.write("\t\t<div id=\"head_menu\">\r\n");
      out.write("\t\t\t<ul class=\"head_ul\">\r\n");
      out.write("\t\t\t\t<li><img src=\"images/logo3.png\" class=\"head_logo\" width=\"55\" /><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/logo_4.png\" width=\"70\" class=\"head_logo_1\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"images/faith.png\" class=\"head_logo1\" /></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\" class=\"head_li\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"head_li\" id=\"head_li_from\"><a\r\n");
      out.write("\t\t\t\t\thref=\"html/business_system.jsp\" class=\"head_font_size\">课程体系</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"head_nav_nav_none\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"html/yewu.html\" class=\"head_font_size\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"head_nav_yw_tx\" class=\"head_li\">业务体系</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/step_in.jsp\" class=\"head_li\">走进KLEE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/time_axis.jsp\" class=\"head_li\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color:#09C;font-weight:bold;\">发展历程</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/developer.jsp\" class=\"head_li\">论坛.活动</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"html/bangzhu.jsp\" class=\"head_li\">帮助</a></li>\r\n");
      out.write("\t\t\t\t");

					String name = (String) session.getAttribute("name");
					if (name == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"html/l_zhuce.jsp\" class=\"DL_zc\">注册</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"entry()\" class=\"DL_\">登录</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"DL_name\" onclick=\"javascript:alert('暂时不能提供查看个人信息')\">欢迎您:");
      out.print(name);
      out.write("</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\" onClick=\"exit()\" class=\"DL_E\">退出</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction exit() {\r\n");
      out.write("\t\t\tvar form = document.myform;\r\n");
      out.write("\t\t\tform.action = \"ExitServlet\";\r\n");
      out.write("\t\t\tform.method = \"post\";\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--登录框-->\r\n");
      out.write("\t<div id=\"entry_box\">\r\n");
      out.write("\t\t<div class=\"dl_box\">\r\n");
      out.write("\t\t\t<div id=\"entry\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t<span id=\"entry_span1\" onClick=\"entryOne()\">请输入用户名</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span3\"></span><span id=\"entry_span3_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"entry_one\" name=\"username\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entryOne()\" onBlur=\"text()\" /><br /> <br /> <br /> <span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span2\" onClick=\"entry_one1()\">请输入登陆密码</span><span\r\n");
      out.write("\t\t\t\t\t\tid=\"entry_span4\"></span><span id=\"entry_span4_1\"></span> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"entry_two\" class=\"entry_style\"\r\n");
      out.write("\t\t\t\t\t\tonFocus=\"entry_one1()\" onBlur=\"text1()\" /><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"GO>>\" id=\"entry_submit\" onClick=\"decision()\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <span><a href=\"javascript:alert('正在全力建设')\"\r\n");
      out.write("\t\t\t\tclass=\"entry_span_1\">忘记密码&gt;&gt;</a></span> -->\r\n");
      out.write("\t\t\t<span><a href=\"html/l_zhuce.jsp\" class=\"entry_span_2\">注册&gt;&gt;</a>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width:1200px;min-height:800px;margin-top:0px;border:0px solid ;position:relative;margin:0px auto;\">\r\n");
      out.write("\t\t<div class=\"divbiao\">梦想的导航者，未来的创造者</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"divyuan\">\r\n");
      out.write("\t\t\t<!--圆形-->\r\n");
      out.write("\t\t\t<span>2015年</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"divshugang\"></div>\r\n");
      out.write("\t\t<!--竖杠-->\r\n");
      out.write("\t\t<div class=\"divdian1\"></div>\r\n");
      out.write("\t\t<div class=\"divdian2\"></div>\r\n");
      out.write("\t\t<div class=\"divdian3\"></div>\r\n");
      out.write("\t\t<div class=\"divdian4\"></div>\r\n");
      out.write("\t\t<div class=\"divdian5\"></div>\r\n");
      out.write("\t\t<div class=\"divdian6\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"divzi1\">11月24日</div>\r\n");
      out.write("\t\t<div class=\"divzi2\">11月25日</div>\r\n");
      out.write("\t\t<div class=\"divzi3\">11月26日</div>\r\n");
      out.write("\t\t<div class=\"divzi4\">12月5日</div>\r\n");
      out.write("\t\t<div class=\"divzi5\">12月9日</div>\r\n");
      out.write("\t\t<div class=\"divzi6\">至今...</div>\r\n");
      out.write("\t\t<div class=\"divkuang1\">四人组建团队，共同商策发展方向</div>\r\n");
      out.write("\t\t<div class=\"divkuang2\">由于对IT行业兴趣浓厚，想起求学的各种艰辛，准备创办网络教学机构，给求学者提供最大的捷径，为在线教育注入更加年轻的血液\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"divkuang3\">正式开始启用“乐启学院”品牌，同时开设多学院，新增网络营销、网页制作、淘宝等课程，开始了多科目的全行业的在线教育发展之路。</div>\r\n");
      out.write("\t\t<div class=\"divkuang4\">\r\n");
      out.write("\t\t\t学院正式更名为乐启教育，启用新的品牌LOGO。\r\n");
      out.write("\t\t\t<!--  团队成员：CEO：贾国瑞  &nbsp;&nbsp; 项目负责人：罗文杰  &nbsp;&nbsp;  保镖：叶博武&nbsp;&nbsp;  软件开发员：付秀鹏 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"divkuang5\">启用全新“四叶草”LOGO，正式更名为KLEE(俄语意为：四叶草)，官网同时更改诸多版块...</div>\r\n");
      out.write("\t\t<div class=\"divkuang6\">不断完善中...</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 版权部分修改版 -->\r\n");
      out.write("\t<div class=\"bottom_banquan\">\r\n");
      out.write("\t\t<div class=\"bottom_bg_color\">\r\n");
      out.write("\t\t\t<div class=\"bottom_box\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"lianxi_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bottom_dizhi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon1.png\" class=\"lianxi_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:viod(0)\" title=\"中国陕西省西安市长安区下北良村西安科技大学高新学院\">中国陕西省西安市长安区下北良村西安科技大学高新学院</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon3.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"tel:15596885995\" title=\"400-888-8888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">400-888-8888</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bottom_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/icon2.png\" class=\"lianxi_img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width:27px;margin-left:-14px;margin-top:-8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <span class=\"bottom_font_lianxi\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"mailto:603049583@qq.com\" title=\"klee@163.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align:left;\">klee@163.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--留言板  -->\r\n");
      out.write("\t\t\t\t<div class=\"bottom_lianxi_right\">\r\n");
      out.write("\t\t\t\t\t<form onsubmit=\"tijiao()\" name=\"from_bus\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bottom_lianxi\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">邮&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"position:relative;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"kong\" class=\"lianxi_right_kuang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"youxiang(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"youxiang_box\" id=\"youxiang_\">邮箱格式有误</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang2\" name=\"kong\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"lianxi_right_font\" width=\"80px\" valign=\"top\">留言内容:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"kong\" cols=\"30\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"lianxi_right_kuang3\" style=\"resize:none;\"></textarea><</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><div class=\"lianxi_right_tijiao\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"liuyan()\">Submit</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom_banquan_bq\">\r\n");
      out.write("\t\t\t<div class=\"bottom_banquan_center\">\r\n");
      out.write("\t\t\t\t<div class=\"banquan_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"center_bq\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>合作公司</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"banquan_bufen\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">Copyright © 2015 xike2-3zu. All\r\n");
      out.write("\t\t\t\t\t\tRightsReserved.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bufen\">西科软件开发二班第三组 版权所有 | 贾国瑞 | 罗文杰 | 叶博武 | 付秀鹏</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--浮动猫链接-->\r\n");
      out.write("\t<div class=\"float_box\">\r\n");
      out.write("\t\t<div class=\"float\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"float_a\">返回顶部 <span class=\"float_bg\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"float1\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"float_a1\">关注微信 <span\r\n");
      out.write("\t\t\t\tclass=\"float_bg1\"></span> <img src=\"images/wx.JPG\" width=\"150\"\r\n");
      out.write("\t\t\t\theight=\"150\" class=\"weixin\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
